'VERSION 1.0 CLASS
'BEGIN
' MultiUse = -1  'True
'Persistable = 0  'NotPersistable
'DataBindingBehavior = 0  'vbNone
'DataSourceBehavior  = 0  'vbNone
' MTSTransactionMode  = 0  'NotAnMTSObject
'END
'Attribute VB_Name = "Seguridad"
'Attribute VB_GlobalNameSpace = False
'Attribute VB_Creatable = True
'Attribute VB_PredeclaredId = False
'Attribute VB_Exposed = True
'Public Class Seguridad

'    Public Function encriptarcandado(ByVal cadena As String) As String
'        encriptarcandado = Encriptarpaso1(cadena)
'    End Function

'    Public Function encriptarllave(ByVal cadena As String) As String
'        encriptarllave = Encriptarpaso2(cadena)
'    End Function
'    Public Function descriptarllave(ByVal cadena As String) As String
'        descriptarllave = Desencriptar(cadena)
'    End Function






